# Generated by Django 4.2.25 on 2025-10-22 17:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "contato",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="Contato"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, null=True, verbose_name="Email"),
                ),
                ("endereco", models.TextField(blank=True, null=True, verbose_name="Endereço")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Peca",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("codigo", models.CharField(max_length=100, unique=True, verbose_name="Código")),
                ("descricao", models.TextField(blank=True, null=True, verbose_name="Descrição")),
                (
                    "pedido",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Número do Pedido"
                    ),
                ),
                ("quantidade", models.IntegerField(verbose_name="Quantidade")),
                (
                    "data_entrega",
                    models.DateField(blank=True, null=True, verbose_name="Data de Entrega"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("novo", "Novo"),
                            ("em_producao", "Em Produção"),
                            ("concluido", "Concluído"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="novo",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                ("metadata", models.JSONField(blank=True, null=True, verbose_name="Metadados")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pecas",
                        to="pecas.cliente",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Peça",
                "verbose_name_plural": "Peças",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(fields=["nome"], name="pecas_clien_nome_d051a8_idx"),
        ),
        migrations.AddIndex(
            model_name="peca",
            index=models.Index(fields=["codigo"], name="pecas_peca_codigo_b03b0c_idx"),
        ),
        migrations.AddIndex(
            model_name="peca",
            index=models.Index(fields=["status"], name="pecas_peca_status_d1d258_idx"),
        ),
        migrations.AddIndex(
            model_name="peca",
            index=models.Index(fields=["data_entrega"], name="pecas_peca_data_en_d843b5_idx"),
        ),
        migrations.AddIndex(
            model_name="peca",
            index=models.Index(fields=["cliente", "status"], name="pecas_peca_cliente_525676_idx"),
        ),
    ]
