# Generated by Django 4.2.25 on 2025-11-03 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("producao", "0001_initial"),
        ("pecas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="peca",
            name="ordem_producao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pecas",
                to="producao.ordemproducao",
                verbose_name="Ordem de Produção",
            ),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(fields=["nome"], name="pecas_clien_nome_d051a8_idx"),
        ),
        migrations.AddIndex(
            model_name="peca",
            index=models.Index(fields=["codigo"], name="pecas_peca_codigo_b03b0c_idx"),
        ),
        migrations.AddIndex(
            model_name="peca",
            index=models.Index(fields=["status"], name="pecas_peca_status_d1d258_idx"),
        ),
        migrations.AddIndex(
            model_name="peca",
            index=models.Index(fields=["data_entrega"], name="pecas_peca_data_en_d843b5_idx"),
        ),
        migrations.AddIndex(
            model_name="peca",
            index=models.Index(fields=["cliente", "status"], name="pecas_peca_cliente_525676_idx"),
        ),
        migrations.AddIndex(
            model_name="peca",
            index=models.Index(fields=["ordem_producao"], name="pecas_peca_ordem_p_ff2db7_idx"),
        ),
    ]
