# Generated by Django 4.2.25 on 2025-11-03 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="Email")),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="Nome"),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Sobrenome"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("is_staff", models.BooleanField(default=False, verbose_name="Membro da equipe")),
                ("is_superuser", models.BooleanField(default=False, verbose_name="Superusuário")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LogAcao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("acao", models.CharField(max_length=100, verbose_name="Ação")),
                (
                    "alvo_tipo",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Tipo do alvo"
                    ),
                ),
                ("alvo_id", models.UUIDField(blank=True, null=True, verbose_name="ID do alvo")),
                ("detalhes", models.JSONField(blank=True, null=True, verbose_name="Detalhes")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Ação",
                "verbose_name_plural": "Logs de Ações",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "created_at"], name="usuarios_lo_usuario_581f6b_idx"
                    ),
                    models.Index(fields=["acao"], name="usuarios_lo_acao_6b8add_idx"),
                    models.Index(
                        fields=["alvo_tipo", "alvo_id"], name="usuarios_lo_alvo_ti_afc6cf_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="usuario",
            index=models.Index(fields=["email"], name="usuarios_us_email_41a027_idx"),
        ),
        migrations.AddIndex(
            model_name="usuario",
            index=models.Index(fields=["is_active"], name="usuarios_us_is_acti_8a269b_idx"),
        ),
    ]
