# Generated by Django 4.2.25 on 2025-10-22 17:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Anexo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("object_id", models.UUIDField()),
                (
                    "arquivo_path",
                    models.CharField(max_length=512, verbose_name="Caminho do Arquivo"),
                ),
                (
                    "nome_original",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Nome Original"
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Tipo MIME"
                    ),
                ),
                (
                    "tamanho",
                    models.IntegerField(blank=True, null=True, verbose_name="Tamanho (bytes)"),
                ),
                ("metadata", models.JSONField(blank=True, null=True, verbose_name="Metadados")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
            ],
            options={
                "verbose_name": "Anexo",
                "verbose_name_plural": "Anexos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Atividade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                ("descricao", models.TextField(blank=True, null=True, verbose_name="Descrição")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("na_fila", "Na Fila"),
                            ("em_andamento", "Em Andamento"),
                            ("concluido", "Concluído"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="na_fila",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                ("prioridade", models.IntegerField(default=0, verbose_name="Prioridade")),
                (
                    "data_inicio",
                    models.DateTimeField(blank=True, null=True, verbose_name="Data de Início"),
                ),
                (
                    "data_fim",
                    models.DateTimeField(blank=True, null=True, verbose_name="Data de Fim"),
                ),
                ("posicao", models.IntegerField(blank=True, null=True, verbose_name="Posição")),
                ("metadata", models.JSONField(blank=True, null=True, verbose_name="Metadados")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
            ],
            options={
                "verbose_name": "Atividade",
                "verbose_name_plural": "Atividades",
                "ordering": ["posicao", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("texto", models.TextField(verbose_name="Texto")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                (
                    "atividade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="atividades.atividade",
                        verbose_name="Atividade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comentário",
                "verbose_name_plural": "Comentários",
                "ordering": ["created_at"],
            },
        ),
    ]
