# Generated by Django 4.2.25 on 2025-10-22 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("producao", "0002_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("pecas", "0001_initial"),
        ("atividades", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comentario",
            name="autor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comentarios",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Autor",
            ),
        ),
        migrations.AddField(
            model_name="atividade",
            name="ordem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="atividades",
                to="producao.ordemproducao",
                verbose_name="Ordem de Produção",
            ),
        ),
        migrations.AddField(
            model_name="atividade",
            name="ordem_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="atividades",
                to="producao.ordemproducaoitem",
                verbose_name="Item de OP",
            ),
        ),
        migrations.AddField(
            model_name="atividade",
            name="peca",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="atividades",
                to="pecas.peca",
                verbose_name="Peça",
            ),
        ),
        migrations.AddField(
            model_name="atividade",
            name="responsavel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="atividades",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsável",
            ),
        ),
        migrations.AddField(
            model_name="anexo",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
            ),
        ),
        migrations.AddField(
            model_name="anexo",
            name="criado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="anexos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AddIndex(
            model_name="comentario",
            index=models.Index(
                fields=["atividade", "created_at"], name="atividades__ativida_a03290_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="atividade",
            index=models.Index(fields=["status"], name="atividades__status_acad34_idx"),
        ),
        migrations.AddIndex(
            model_name="atividade",
            index=models.Index(
                fields=["responsavel", "status"], name="atividades__respons_763173_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="atividade",
            index=models.Index(fields=["ordem", "status"], name="atividades__ordem_i_04a31f_idx"),
        ),
        migrations.AddIndex(
            model_name="atividade",
            index=models.Index(fields=["prioridade"], name="atividades__priorid_67342b_idx"),
        ),
        migrations.AddIndex(
            model_name="anexo",
            index=models.Index(
                fields=["content_type", "object_id"], name="atividades__content_375667_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anexo",
            index=models.Index(fields=["criado_por"], name="atividades__criado__1b90f7_idx"),
        ),
    ]
