# Generated by Django 4.2.25 on 2025-10-22 17:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pecas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdemProducao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "numero",
                    models.CharField(max_length=50, unique=True, verbose_name="Número da OP"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data de Criação"),
                ),
                (
                    "data_inicio_prevista",
                    models.DateField(blank=True, null=True, verbose_name="Data Início Prevista"),
                ),
                (
                    "data_fim_prevista",
                    models.DateField(blank=True, null=True, verbose_name="Data Fim Prevista"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberta", "Aberta"),
                            ("em_andamento", "Em Andamento"),
                            ("pausada", "Pausada"),
                            ("concluida", "Concluída"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="aberta",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
            ],
            options={
                "verbose_name": "Ordem de Produção",
                "verbose_name_plural": "Ordens de Produção",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrdemProducaoItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("quantidade", models.IntegerField(verbose_name="Quantidade")),
                (
                    "quantidade_produzida",
                    models.IntegerField(default=0, verbose_name="Quantidade Produzida"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_producao", "Em Produção"),
                            ("pausado", "Pausado"),
                            ("concluido", "Concluído"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendente",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "lote",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="Lote"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                (
                    "ordem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="producao.ordemproducao",
                        verbose_name="Ordem de Produção",
                    ),
                ),
                (
                    "peca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="op_itens",
                        to="pecas.peca",
                        verbose_name="Peça",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Ordem de Produção",
                "verbose_name_plural": "Itens de Ordens de Produção",
                "ordering": ["ordem", "-created_at"],
            },
        ),
    ]
