# Generated by Django 4.2.25 on 2025-10-22 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("producao", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ordemproducao",
            name="criado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ops_criadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AddIndex(
            model_name="ordemproducaoitem",
            index=models.Index(fields=["ordem", "status"], name="producao_or_ordem_i_a548f1_idx"),
        ),
        migrations.AddIndex(
            model_name="ordemproducaoitem",
            index=models.Index(fields=["peca"], name="producao_or_peca_id_978560_idx"),
        ),
        migrations.AddIndex(
            model_name="ordemproducao",
            index=models.Index(fields=["numero"], name="producao_or_numero_0dcde3_idx"),
        ),
        migrations.AddIndex(
            model_name="ordemproducao",
            index=models.Index(fields=["status"], name="producao_or_status_c4638c_idx"),
        ),
        migrations.AddIndex(
            model_name="ordemproducao",
            index=models.Index(
                fields=["criado_por", "status"], name="producao_or_criado__386be7_idx"
            ),
        ),
    ]
