# Generated by Django 4.2.25 on 2025-11-03 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("producao", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ordemproducao",
            name="criado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ops_criadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AddIndex(
            model_name="ordemproducao",
            index=models.Index(fields=["codigo"], name="producao_or_codigo_9b9087_idx"),
        ),
        migrations.AddIndex(
            model_name="ordemproducao",
            index=models.Index(fields=["status"], name="producao_or_status_c4638c_idx"),
        ),
        migrations.AddIndex(
            model_name="ordemproducao",
            index=models.Index(fields=["cliente"], name="producao_or_cliente_2389ed_idx"),
        ),
        migrations.AddIndex(
            model_name="ordemproducao",
            index=models.Index(
                fields=["created_at", "status"], name="producao_or_created_f480eb_idx"
            ),
        ),
    ]
