# Generated by Django 4.2.25 on 2025-10-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producao", "0002_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ordemproducao",
            index=models.Index(
                fields=["data_fim_prevista", "status"], name="producao_or_data_fi_35b23e_idx"
            ),
        ),
    ]
