# Generated by Django 4.2.25 on 2025-11-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producao", "0003_ordemproducao_responsavel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordemproducao",
            name="status",
            field=models.CharField(
                choices=[
                    ("aberta", "Aberta"),
                    ("em_andamento", "Em Andamento"),
                    ("pausada", "Pausada"),
                    ("concluida", "Concluída"),
                    ("cancelada", "Cancelada"),
                ],
                default="aberta",
                max_length=30,
                verbose_name="Status",
            ),
        ),
    ]
